language: node_js

node_js:
  - "8"

install:
  - yarn

script:
  - yarn build

deploy:
  provider: script
  skip_cleanup: true
  script: chmod +x ./travis-deploy.sh && ./travis-deploy.sh
  on:
    tags: true
